version: 2
sources:
  - name: raw_jaffle_shop
    database: raw
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _etl_loaded_at    
    schema: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - not_null
              - unique
      - name: orders

  - name: raw_stripe
    database: raw
    schema: stripe
    tables:
      - name: payment
        columns:
          - name: orderid
            tests:
              - not_null    